name: Cypress Tests

on:
  push:
    schedule:
      - cron: '0 0 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Cypress run
        uses: cypress-io/github-action@master
        with:
          command: npm run test
          parallel: true
          browser: chrome
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
      # - name: Slack Notification
      #   uses: rtCamp/action-slack-notify@v2
      #   if: always()
      #   env:
      #     SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}} 
      #     SLACK_USERNAME: owais
      #     SLACK_TITLE: "Environment: Production \n Build Status: ${{job.status}}"
      #     SLACK_COLOR: ${{job.status}}